### ISSUE TITLE
Password "Complexity requirements are not met" false-positive

### ISSUE THREAD

**Issue by armab** [StackStorm/st2installer#26]
Password fails validation if it contains special characters outside of listed `[a-zA-Z0-9!=@#$%\^&*()_"` in [regular expression](https://github.com/StackStorm/st2installer/blob/5bd1e98fab59828578c0bee81cd1850481fd2ff3/public/scripts/main.js#L318).

For example `Stackstorm+1` password is not validated, see: https://regex101.com/r/pR5dE5/1

Don't know the actual reason to white-list characters. Maybe it's ok to allow _any_ character in password?

**Comment by emedvedev** [comment]
It's ok to allow any, but to see if at least one special character has been included, we still need a list of special characters. :) So we just have to make a bigger list unless anyone has other suggestions.

**Comment by jfryman** [comment]
I have to wonder if there is a small library to do this for us. It is JavaScript, after all.

**Comment by emedvedev** [comment]
So, I found out where I was wrong: we don't actually _require_ special characters at all, just length of 8+, at least one letter and at least one digit. I broke the regex matching down to simpler validations: letters, digits, length. Now we don't care what other characters are there as long as our requirements are met. I think that this is the right way.

Thanks @armab for pointing that out!
