### ISSUE TITLE
User uploaded keys failed to attach, causing failure

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#27]
User report from `stackstorm-community`:

When a user attempts to upload a SSH key, presented with missing HTTP params. Trace dump at : https://gist.github.com/jfryman/0993c93e0228a84f4f91

/cc @emedvedev

**Comment by emedvedev** [comment]
I'll look into it today or tomorrow. Maybe pecan got updated with some breaking changes.

**Comment by emedvedev** [comment]
Fixed it, yay. Turns out wrong fields were referenced if you try to upload SSH keys.
