### ISSUE TITLE
st2installer should manage answers.yaml

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#28]
Up to now, `st2installer` is relying on the underlying OS to have the `answers.yaml` file created by Puppet. In some cases, this file isn't created at boot.

To that end, the installer should be able to mange this file on its own via `sudo`. If this file doesn't exist with the right permissions, the `st2installer` should make sure it can write to it to avoid issues like this:

![screen shot 2015-09-10 at 5 25 53 pm](https://cloud.githubusercontent.com/assets/20028/9801617/c6ac3c24-57d9-11e5-8e48-0cb18e76c46b.png)

**Comment by emedvedev** [comment]
Fixed it: checking for write access and giving permissions with sudo if can't write.
