### ISSUE TITLE
Installer does not currently execute

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#36]
After filling in all details, and pressing the 'install' button on the last page (ChatOps), user is presented with pecan errors and processing does not occur

![screen shot 2015-09-17 at 9 57 46 am](https://cloud.githubusercontent.com/assets/20028/9940198/2390c8ee-5d23-11e5-8548-403eaf6ec9d1.png)

/cc @DoriftoShoes @emedvedev

**Comment by manasdk** [comment]
Fixed https://github.com/StackStorm/st2installer/pull/37
