### ISSUE TITLE
Installer throws blank SSH keys dialog box

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#38]
During installation, Installer throws up two different popups with SSH keys. The second is populated properly, but a first popup appears and is a bit confusing. (See below)

<img width="541" alt="stackstorm_installer" src="https://cloud.githubusercontent.com/assets/20028/9962226/41ba4238-5dea-11e5-896c-a88c001b05fa.png">

**Comment by emedvedev** [comment]
It's actually shown twice? You click "got it" and instantly see another one?

**Comment by jfryman** [comment]
The other way around, actually. I got this ^^^, and then instantly saw the correct one.

I checked the server between these states, and the keys existed. So, this was a weird popup.

**Comment by jfryman** [comment]
Might actually be related to SSL trust still. 

![stackstorm_installer](https://cloud.githubusercontent.com/assets/20028/9966034/f0497674-5dff-11e5-997e-0aa296272c00.png)

**Comment by jfryman** [comment]
This was solved when a self-signed CA was introduced.
