### ISSUE TITLE
Displaying CA Dialog does not appear to be working

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#39]
While testing https://github.com/StackStorm/st2installer/pull/33 today, the CA dialog box did not appear to pop up. Tested a few times on AMI m4.large with same results.

**Comment by emedvedev** [comment]
Can you manually download /ssl/st2_root_ca.cer when puppet stops? Pretty much the only way this popup doesn't show up is a failed HEAD request to the file.

**Comment by jfryman** [comment]
Yes. I can manually download the file.

**Comment by jfryman** [comment]
So, this is again a matter of trust.

![stackstorm_installer](https://cloud.githubusercontent.com/assets/20028/9966034/f0497674-5dff-11e5-997e-0aa296272c00.png)

If I don't trust the CA, how can I poll an endpoint I don't trust for trust credentials.

I think it might be better to instead of poll just use the user input to toggle the CA dialog.

**Comment by emedvedev** [comment]
Well, it's the same endpoint that installer is running on, so trust shouldn't be an issue, you already accepted the cert. I'll change it to using the form input, just wanted to avoid possible bugs when we don't have a CA to download (for any reason) but still show the message with a link.

**Comment by jfryman** [comment]
This was solved when a self-signed CA was introduced.
