### ISSUE TITLE
Redirect loop / internal error after visiting installer on successful install

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2installer#80]
If you visit installer after the installation completes, you will get back internal error due to redirection loop.

I believe this is related to the install lock, but I didn't have the time to dig in yet.

![selection_275](https://cloud.githubusercontent.com/assets/125088/10743294/745c74de-7c32-11e5-9127-ea259e233c64.png)

**Comment by emedvedev** [comment]
Fixed in #90
