### ISSUE TITLE
Remove "local IRC server" option

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#93]
Until we have the chance to implement it, I believe we should remove the option in the ChatOps section. It's confusing because it does not reflect a reality of any sort. We can/should get around to this, but until then... :fire:

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1450273550014667

**Comment by jfryman** [comment]
@emedvedev you're too fast! :car: :dash:
